#Buildphase
# Maven-Image mit Java 21 um das Projekt zu bauen
FROM maven:3.9.9-eclipse-temurin-21 AS build

# Setze das Arbeitsverzeichnis im Container auf /app
WORKDIR /app

# Kopiert den gesamten Backend-Code ins Image
COPY . .

# Führe den Maven-Build aus und überspringe Tests 
RUN mvn clean package -DskipTests

#Laufzeitphase
# Verwende ein schlankes Java 21 JDK-Image für die Ausführung
FROM eclipse-temurin:21-jdk

# Setze das Arbeitsverzeichnis im Container auf /app
WORKDIR /app

# Kopiert die gebaute JAR-Datei aus der Build-Phase in das neue Image
COPY --from=build /app/target/*.jar app.jar

# Öffne Port 8080
EXPOSE 8080

# Startet die Anwendung beim Containerstart
ENTRYPOINT ["java", "-jar", "app.jar"]
